#!/bin/bash

BASH_CONFIG_PATH=${XDG_CONFIG_HOME:=$HOME/.config}/bash

# ----------------------------------------------------------------------
# | Helper Functions                                                   |
# ----------------------------------------------------------------------

enable_programmable_completion() {

    # Enable programmable completion features
    # http://tldp.org/LDP/abs/html/tabexpansion.html
    if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
        source /etc/bash_completion
    fi
}

source_bash_files() {

    local file=""
    local i=""

    source $BASH_CONFIG_PATH/bash_exports
    source $BASH_CONFIG_PATH/bash_aliases
    source $BASH_CONFIG_PATH/bash_options
    source $BASH_CONFIG_PATH/bash_logout
    source $BASH_CONFIG_PATH/bash_prompt
    source $BASH_CONFIG_PATH/bash_functions
}

# ----------------------------------------------------------------------
# | Main                                                               |
# ----------------------------------------------------------------------

main() {
    source_bash_files
    enable_programmable_completion
}

main

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Unset functions in order to not pollute the global space
unset -f enable_programmable_completion
unset -f main
unset -f source_bash_files

# Clear system messages (e.g.: system copyright notice, the
# date and time of the last login, the message of the day, etc.)
clear
