[ -n "$PS1" ] && source ~/.bash_profile


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
[[ -e ~/.phpbrew/bashrc ]] && source ~/.phpbrew/bashrc
source /home/george/Code/everything/infrastructure/vagrant/dev-env/.hsderc_local

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
