" Automatically detect file types.
filetype plugin indent on

let $VIM_CONFIG_PATH = exists($XDG_CONFIG_HOME) ? $XDG_CONFIG_HOME.'/vim' : $HOME.'/.config/vim'

source $VIM_CONFIG_PATH/xdg.vim

set runtimepath=$VIM_CONFIG_PATH,$VIM_CONFIG_PATH/after,$VIM,$VIMRUNTIME

source $VIM_CONFIG_PATH/plugins.vim
source $VIM_CONFIG_PATH/config.vim
